/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package demineur;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author dimitriseaborn
 */
public class GamePanel extends javax.swing.JPanel {

    private Case[][] grid;
    private int timerSecond;
    private ScheduledExecutorService timerExecutor;
    private int mineNumber;
    public boolean isOver = false;
    public boolean isFirstMovePlayed = false;

    /**
     * Creates new form gamePannel
     *
     * @param sizeX
     * @param sizeY
     * @param mineNumber
     */
    public GamePanel(int sizeX, int sizeY, int mineNumber) {
        initComponents();
        setupGrid(sizeX, sizeY, mineNumber);
        setupGUI(sizeX, sizeY);
        timerSecond = 0;
        setupTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        timeLabel = new javax.swing.JLabel();
        mineLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        hintButton = new javax.swing.JButton();
        gridPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(534, 50));
        jPanel1.setLayout(new java.awt.GridLayout(1, 6, 5, 0));

        backButton.setText("Retour");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        jPanel1.add(filler5);

        timeLabel.setText("Temps:");
        jPanel1.add(timeLabel);
        jPanel1.add(mineLabel);
        jPanel1.add(filler3);

        hintButton.setText("Indice");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });
        jPanel1.add(hintButton);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        gridPanel.setLayout(new java.awt.GridLayout(1, 0));
        add(gridPanel, java.awt.BorderLayout.CENTER);
        add(filler1, java.awt.BorderLayout.PAGE_END);
        add(filler6, java.awt.BorderLayout.LINE_START);
        add(filler7, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        App.displayMainWindow();
    }//GEN-LAST:event_backButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        getHint();
    }//GEN-LAST:event_hintButtonActionPerformed

    private void setupGrid(int sizeX, int sizeY, int mineNumber) {
        grid = new Case[sizeX][sizeY];
        //Setup grid with all 0
        for (int x = 0; x < sizeX; x++) {
            for (int y = 0; y < sizeY; y++) {
                grid[x][y] = new Case(x, y, 0, sizeX, sizeY);
            }
        }

        //add mines randomly
        this.mineNumber = mineNumber;
        List<Case> caseList = new ArrayList<>();
        for (Case[] row : grid) {
            caseList.addAll(Arrays.asList(row));
        }
        Collections.shuffle(caseList);
        for (int i = 0; i < mineNumber;) {
            if (caseList.get(i).value != -1) {
                caseList.get(i).value = -1;
                i++;
            }
        }

        //set values of non mines
        Case current;
        for (int x = 0; x < sizeX; x++) {
            for (int y = 0; y < sizeY; y++) {
                //for each case
                current = grid[x][y];
                int surroundingMines = 0;
                if (!current.isMine()) {
                    //for each surrounding case
                    for (Case neighbour : getNeighbours(x, y)) {
                        if (neighbour.isMine()) {
                            surroundingMines++;
                        }

                    }
                    current.value = surroundingMines;
                    current.updateColor();
                }
                //TODO: remove this
                current.updateColor();
            }
        }
        //TODO: remove this
//        System.out.println(Arrays.deepToString(grid));
    }

    private void setupGUI(int sizeX, int sizeY) {

        gridPanel.setLayout(new java.awt.GridLayout(sizeX, sizeY, 0, 0));

        for (int x = 0; x < sizeX; x++) {
            for (int y = 0; y < sizeY; y++) {
                gridPanel.add(grid[x][y].button);
            }
        }

        updateMineLeft();
    }

    public void reveal(int x, int y) {
        grid[x][y].reveal();
    }

    public void revealAroundIfCompleted(int x, int y) {
        int surroundingFlags = 0;
        for (Case neighbour : getNeighbours(x, y)) {
            if (neighbour.isFlagged) {
                surroundingFlags++;
            }
        }
        if (surroundingFlags == grid[x][y].value) {
            for (Case neighbour : getNeighbours(x, y)) {
                if (neighbour.isMine() && !neighbour.isFlagged) {
                    App.gameOver();
                } else {
                    neighbour.reveal();
                }
            }
        }
    }

    private void setupTimer() {
        Runnable updateTimer = new Runnable() {
            @Override
            public void run() {
                timeLabel.setText("Temps: " + timerSecond);
                timerSecond++;
            }
        };
        timerExecutor = Executors.newScheduledThreadPool(1);
        timerExecutor.scheduleAtFixedRate(updateTimer, 0, 1, TimeUnit.SECONDS);
    }

    public void gameOver() {
        if (isOver) {
            return;
        }
        timerExecutor.shutdown();
        for (int x = 0; x < grid.length; x++) {
            for (int y = 0; y < grid[0].length; y++) {
                grid[x][y].reveal();
            }
        }
        isOver = true;
    }

    public void updateMineLeft() {
        int numFlaggedMines = 0;
        for (Case[] cases : grid) {
            for (Case aCase : cases) {
                if (aCase.isFlagged) {
                    numFlaggedMines++;
                }
            }
        }
        mineLabel.setText("Mines: " + (mineNumber - numFlaggedMines));
    }

    public void checkIfWon() {
        if (isOver) {
            return;
        }
        boolean hasCasesLeft = false;
        for (Case[] columns : grid) {
            if (hasCasesLeft) {
                break;
            }
            for (Case aCase : columns) {
                if (!aCase.isRevealed && !aCase.isMine()) {
                    hasCasesLeft = true;
                    break;
                }
            }
        }
        if (!hasCasesLeft) {
            timerExecutor.shutdown();
            App.gameWon(timerSecond);
        }
    }

    private void getHint() {
        List<Case> caseList = new ArrayList<>();
        for (Case[] row : grid) {
            caseList.addAll(Arrays.asList(row));
        }
        Collections.shuffle(caseList);
        for (Case randomCase : caseList) {
            //For random cases
            int numRevealedNeighbour = 0;
            Case[] neighbourgs = getNeighbours(randomCase);
            for (Case neighbour : neighbourgs) {
                if (neighbour.isRevealed) {
                    numRevealedNeighbour++;
                }
            }
            if (numRevealedNeighbour != 0 && !randomCase.isRevealed) {
                randomCase.reveal();
                randomCase.blink(new Color(50, 255, 75));
                break;
            }
        }
        checkIfWon();
    }

    public Case[] getNeighbours(Case aCase) {
        return getNeighbours(aCase.coordX, aCase.coordY);
    }

    private Case[] getNeighbours(int x, int y) {
        final int[] offsetX = {-1, 0, 1};
        final int[] offsetY = {-1, 0, 1};
        final List<Case> cases = new ArrayList<>();

        for (int xOffset : offsetX) {
            for (int yOffset : offsetY) {
                //for each surrounding case
                if (!(x + xOffset < 0 || x + xOffset >= grid.length || y + yOffset < 0 || y + yOffset >= grid[0].length)) {
                    if (!(xOffset == 0 && yOffset == 0)) {
                        cases.add(grid[x + xOffset][y + yOffset]);
                    }
                }
            }
        }
        final Case[] casesArray = new Case[cases.size()];
        for (int i = 0; i < cases.size(); i++) {
            casesArray[i] = cases.get(i);
        }
        return casesArray;
    }

    public void playFirstMove(int x, int y) {
        isFirstMovePlayed = true;
        if (!"classic".equals(App.settings.get("gamemode", "classic"))) {
            grid[x][y].isRevealed = true;
            makeNotMine(x, y);
            for (Case neighbour : getNeighbours(x, y)) {
//                neighbour.isRevealed = true;   
                makeNotMine(neighbour.coordX, neighbour.coordY);
            }
        }
        grid[x][y].isRevealed = false;
//        for (Case neighbour : getNeighbours(x, y)) {
//            neighbour.isRevealed = false;
//        }
        grid[x][y].clickCase();
    }

    public void makeNotMine(Case aCase) {
        makeNotMine(aCase.coordX, aCase.coordY);
    }

    private void makeNotMine(int x, int y) {
        //FIXME: not working consistently when ridiculously high proportion of mine
        Case oldCase = grid[x][y];

        if (oldCase.isMine()) {

            List<Case> caseList = new ArrayList<>();
            for (Case[] row : grid) {
                caseList.addAll(Arrays.asList(row));
            }
            Collections.shuffle(caseList);
            for (int i = 0; i < caseList.size(); i++) {
                //For random cases
                Case randomCase = caseList.get(i);
                int numRevealedNeighbour = 0;
                Case[] newCaseNeighbours = getNeighbours(randomCase);
                for (Case neighbour : newCaseNeighbours) {
                    if (neighbour.isRevealed) {
                        numRevealedNeighbour++;
                    }
                }
                if (numRevealedNeighbour == 0 && !randomCase.isRevealed && !randomCase.isMine()) {
                    //Player has no info on the case and it is not a mine
                    swap(oldCase, randomCase);
                    break;
                }
            }
        }
    }

    public Case canBeDeduced(Case aCase) {
        return canBeDeduced(aCase.coordX, aCase.coordY);
    }

    public Case canBeDeduced(int x, int y) {

        //If revealed, return
        if (grid[x][y].isRevealed) {
            return null;
        }
        Case[] neighbourgs = getNeighbours(x, y);
        List<Case> infoAvailable = new ArrayList<>();
        Case swappableWith = null;

        //Check what info we have on the mine
        for (Case neighbourg : neighbourgs) {
            if (neighbourg.isRevealed && !neighbourg.isMine()) {
                infoAvailable.add(neighbourg);
            }
        }

        /*Check if all info is also applicable to another case up to 2 tile away for cases like this:
        *  ?|X|X
        *  -----
        *  X|7|X
        *  -----
        *  X|X|?
         */
        for (Case neighbour1 : neighbourgs) {
            for (Case neighbour2 : getNeighbours(neighbour1)) {
                if (!neighbour2.isRevealed) {
                    List<Case> neighbourInfoAvailable = new ArrayList<>();

                    //Check what info the neighbour has
                    for (Case neighbourNeighbour : getNeighbours(neighbour2)) {
                        //If the neigbour is a mine, it gives no info
                        if (neighbourNeighbour.isRevealed && !neighbourNeighbour.isMine()) {
                            neighbourInfoAvailable.add(neighbourNeighbour);
                        }
                    }

                    //if all the info we have on the case can also apply to another case, it can't be deduced if the two cases are not of the same type
                    if (neighbourInfoAvailable.equals(infoAvailable)) {
                        if (neighbour2.isMine() != grid[x][y].isMine()) {
                            swappableWith = neighbour2;
                            break;
                        }
                    }
                }
            }
        }
        return swappableWith;
    }

    public void swap(Case case1, Case case2) {
        Case[] case1Neighbours = getNeighbours(case1);
        Case[] case2Neighbours = getNeighbours(case2);
        int case1Value = case1.value;

        if (case2.isMine()) {
            case1.value = -1;
        } else {
            int case1NeighbourMines = 0;
            for (Case neighbour1 : case1Neighbours) {
                if (neighbour1.isMine()) {
                    case1NeighbourMines++;
                }
            }
            case1.value = case1NeighbourMines;
            case1.updateColor();
        }

        if (case1Value == -1) {
            case2.value = -1;
        } else {
            int case2NeighbourMines = 0;
            for (Case neighbour2 : case2Neighbours) {
                if (neighbour2.isMine()) {
                    case2NeighbourMines++;
                }
            }
            case2.value = case2NeighbourMines;
            case2.updateColor();
        }

        //Update case 1 neighbours
        for (Case neighbour : case1Neighbours) {
            if (!neighbour.isMine()) {
                int caseNeighbourMines = 0;
                for (Case neighbour1 : getNeighbours(neighbour)) {
                    if (neighbour1.isMine()) {
                        caseNeighbourMines++;
                    }
                }
                neighbour.value = caseNeighbourMines;
                neighbour.updateColor();
            }
        }
        //Update case 2 neighbours
        for (Case neighbour : case2Neighbours) {
            if (!neighbour.isMine()) {
                int caseNeighbourMines = 0;
                for (Case neighbour1 : getNeighbours(neighbour)) {
                    if (neighbour1.isMine()) {
                        caseNeighbourMines++;
                    }
                }
                neighbour.value = caseNeighbourMines;
                neighbour.updateColor();
            }
        }

        //TODO: remove this?
        if (App.settings.get("debugMode", "Désactivé").equals("Activé")) {
            case1.blink(new Color(0, 0, 255));
            case2.blink(new Color(255, 0, 0));
        }
    }

    public boolean isMoveRandom(Case caseClicked) {
        List<Case> borderCases = new ArrayList<>();
        boolean isNextMoveRandom = true;
        List<Case> caseBlock = new ArrayList<>();
        boolean blockComplete = false;

        caseBlock.add(caseClicked);
        while (!blockComplete) {
            boolean changed = false;
            for (Case aCase : new ArrayList<>(caseBlock)) {
                for (Case neighbour : getNeighbours(aCase)) {
                    if (!neighbour.isRevealed && !caseBlock.contains(neighbour)) {
                        caseBlock.add(neighbour);
                        changed = true;
                    }
                }
            }
            if (!changed) {
                blockComplete = true;
            }
        }

        for (Case aCase : caseBlock) {
            for (Case neighbour : getNeighbours(aCase)) {
                if (neighbour.isRevealed) {
                    borderCases.add(aCase);
                    break;
                }
            }
        }

        for (Case borderCase : borderCases) {
            //Check if not a mine because mines can't be properly revealed
            if (!borderCase.isMine() && canBeDeduced(borderCase) == null && !borderCase.isRevealed) {
                System.out.println("d");
                isNextMoveRandom = false;
                break;
            }
        }

        return isNextMoveRandom;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPanel gridPanel;
    private javax.swing.JButton hintButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mineLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

}
